[project]
name = "cimol"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.40.59",
    "dotenv>=0.9.9",
    "kaggle>=1.7.4.5",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
]
